# ベースイメージとしてnodeを使用
FROM node:14

# 作業ディレクトリを設定
WORKDIR /app

# 必要なファイルをコピー
COPY . .

# パッケージのインストール
RUN npm install

# Laravel Echo Serverのインストール
RUN npm install -g laravel-echo-server

# Laravel Echo Server設定ファイルをコピー
COPY laravel-echo-server.json /app/laravel-echo-server.json

# Laravel Echo Serverを起動
CMD ["laravel-echo-server", "start", "--config", "/app/laravel-echo-server.json"]
